### PR TITLE
summon no longer buffers wrapped process stdout output [CONJ-4705]

### LINKED ISSUE #63: summon is buffering all of the process stdout output
We recently discovered that `summon` memory usage can increase significantly over the course of its lifetime. By looking at the code, it seems that it is tee-ing stdout to an internal buffer. For long running processes that prints to stdout (like a server using a console appender for example) or any process that writes a lot to stdout, this can lead to very high memory consumption by `summon` and ultimately, the death of the process.

To reproduce, use a script like 

```
#!/bin/sh

while true; do cat SOME_BIG_FILE; done
```
Then run this script with `summon`.

Found in `summon version 0.6.5`

### PR DESCRIPTION
**Pull request by dustinmm80**
Closes #63.

Removed the buffer that captured stdout when running the subprocess that summon wraps. This was mostly put in place to make testing easier. The new `captureStdout` test helped makes this buffering unnecessary.

https://jenkins.conjur.net/job/cyberark--summon/job/fix-mem-leak/

### CODE REVIEW

File: command/action.go [hunk 1]
```diff
@@ -121,7 +122,7 @@ EnvLoop:
 					continue EnvLoop
 				}
 			}
-			return "Error fetching variable " + envvar.string, envvar.error
+			return fmt.Errorf("Error fetching variable %v: %v"+envvar.string, envvar.error)
```
Comment (kgilpin) [inline command/action.go]: I think this should be: `return fmt.Errorf("Error fetching variable %v: %v", envvar.string, envvar.error)`

File: command/action_test.go [hunk 2]
```diff
@@ -1,58 +1,74 @@
...
+			err := runAction(&ActionConfig{
 				Args:       []string{"printenv", "MYVAR"}, // args
 				Provider:   providerPath,                  // provider
 				Filepath:   "",                            // filepath
 				YamlInline: "MYVAR: !var error",           // yaml inline
 				Subs:       map[string]string{},           // subs
 				Ignores:    []string{},                    // ignore
 			})
+
 			So(err, ShouldNotBeNil)
```
Comment (kgilpin) [inline command/action_test.go]: An assertion here on the error message probably would have caught the format bug above.

File: command/action_test.go [hunk 3]
```diff
@@ -161,3 +182,18 @@ func TestReturnStatusOfError(t *testing.T) {
...
+
+func captureStdout(f func()) string {
+	old := os.Stdout
+	r, w, _ := os.Pipe()
+	os.Stdout = w
+
+	f()
+
+	w.Close()
+	os.Stdout = old
```
Comment (kgilpin) [inline command/action_test.go]: I think this should be in a `defer`

File: command/action_test.go (hunk 2 above)
Comment (dustinmm80) [reply command/action_test.go]: Looks like you added this, thanks!

`So(err.Error(), ShouldEqual, "Error fetching variable MYVAR: exit status 1")`
